"""
The Named Story - Cover Wrap Generator
=======================================
Generates the hardcover cover wrap PDF for Gelato printing.
This is a SEPARATE file from the interior pages.

Gelato hardcover photobooks require two files:
  1. Interior pages PDF (generated by generate_book.py) - files[].type = "default"
  2. Cover wrap PDF (generated by THIS script)          - files[].type = "cover"

The cover wrap is a single wide page laid out as:
  [Bleed] [Back Cover] [Joint] [Spine] [Joint] [Front Cover] [Bleed]

Cover Dimensions (from Gelato API for 210x280mm / 8x11" hardcover):
  - These are fetched at runtime via the Gelato Cover Dimensions API
  - Fallback defaults are provided for 30-page books
  - Spine width varies by page count (thicker books = wider spine)

Front Cover: cover.jpg + personalized title text (FULL BLEED edge-to-edge)
Back Cover:  scene-09.jpg + Isaiah 43:1 quote + branding (FULL BLEED edge-to-edge)
Spine:       Solid color with book title (optional)

Usage:
    python generate_cover.py --name "Dominic" --variant "boy-fair-blonde"
    python generate_cover.py --name "Dominic" --variant "boy-fair-blonde" --output cover.pdf
"""

import os
import argparse
import json
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm, inch
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ============================================================
# GELATO COVER DIMENSIONS
# ============================================================
# Default dimensions for 210x280mm (8x11") hardcover, 30 pages
# These should be verified by calling the Gelato Cover Dimensions API:
#   GET https://product.gelatoapis.com/v3/products/{productUid}/cover-dimensions?pageCount=30
#
# Layout (left to right):
#   bleed | back content | joint | spine | joint | front content | bleed
#
# All values in mm

DEFAULT_DIMS = {
    "measureUnit": "mm",
    "wraparoundInsideSize": {"width": 618.0, "height": 256.0, "left": 0, "top": 0, "thickness": 17},
    "wraparoundEdgeSize":   {"width": 584.0, "height": 222.0, "left": 17, "top": 17, "thickness": 3},
    "contentBackSize":      {"width": 278.0, "height": 216.0, "left": 20, "top": 20},
    "jointBackSize":        {"width": 8, "height": 216.0, "left": 298.0, "top": 20},
    "spineSize":            {"width": 6, "height": 216.0, "left": 306.0, "top": 20},
    "jointFrontSize":       {"width": 8, "height": 216.0, "left": 312.0, "top": 20},
    "contentFrontSize":     {"width": 278.0, "height": 216.0, "left": 320.0, "top": 20},
}


def get_cover_dimensions(gelato_api_key=None, product_uid=None, page_count=30):
    """
    Fetch cover dimensions from Gelato API, or return defaults.

    If gelato_api_key is provided, queries the API for exact dimensions.
    Otherwise returns DEFAULT_DIMS.
    """
    if gelato_api_key and product_uid:
        try:
            import urllib.request
            url = f"https://product.gelatoapis.com/v3/products/{product_uid}/cover-dimensions?pageCount={page_count}"
            req = urllib.request.Request(url, headers={"X-API-KEY": gelato_api_key})
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read().decode())
                print(f"  \u2713 Fetched cover dimensions from Gelato API ({page_count} pages)")
                return data
        except Exception as e:
            print(f"  \u26a0 Could not fetch Gelato dimensions: {e}")
            print(f"  \u2192 Using default dimensions for {page_count}-page book")

    return DEFAULT_DIMS


# ============================================================
# COLORS - Match the book aesthetic
# ============================================================
CREAM       = HexColor("#fdf6ec")
DARK_BROWN  = HexColor("#3d2b1f")
WARM_BROWN  = HexColor("#5a3a10")
GOLD        = HexColor("#c9a96e")
SOFT_GREY   = HexColor("#999999")
WHITE       = HexColor("#ffffff")
SPINE_COLOR = HexColor("#3d2b1f")  # Dark brown spine


# ============================================================
# FONT SETUP - Same as generate_book.py
# ============================================================
FONTS_DIR = os.environ.get("FONTS_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "fonts"))

F_REG  = "BookSerif"
F_IT   = "BookSerif-Italic"
F_BOLD = "BookSerif-Bold"
F_SEMI = "BookSerif-SemiBold"


def register_fonts():
    global F_REG, F_IT, F_BOLD, F_SEMI
    fonts = {
        F_REG:  "CormorantGaramond-Regular.ttf",
        F_IT:   "CormorantGaramond-Italic.ttf",
        F_BOLD: "CormorantGaramond-Bold.ttf",
        F_SEMI: "CormorantGaramond-SemiBold.ttf",
        "BookSerif-BoldItalic": "CormorantGaramond-BoldItalic.ttf",
    }
    ok = True
    for name, fn in fonts.items():
        p = os.path.join(FONTS_DIR, fn)
        if os.path.exists(p):
            pdfmetrics.registerFont(TTFont(name, p))
        else:
            ok = False
    if not ok:
        F_REG  = "Helvetica"
        F_IT   = "Helvetica-Oblique"
        F_BOLD = "Helvetica-Bold"
        F_SEMI = "Helvetica-Bold"
        print("Warning: Custom fonts not found, using Helvetica fallback")


# ============================================================
# TEXT HELPERS
# ============================================================
def wrap_text(c, text, font, size, max_w):
    """Word-wrap text into lines that fit within max_w."""
    words = text.split()
    lines, cur = [], ""
    for w in words:
        t = f"{cur} {w}" if cur else w
        if c.stringWidth(t, font, size) <= max_w:
            cur = t
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


# ============================================================
# COVER RENDERERS
# ============================================================
def render_front_cover(c, name, img_path, img_x, img_y, img_w, img_h, txt_x, txt_y, txt_w, txt_h):
    """
    Render the front cover: full-bleed cover.jpg with title overlay.

    img_x/y/w/h = image bounds (full bleed, extends to page edge for edge-to-edge printing)
    txt_x/y/w/h = text safe area (content area, inside trim to avoid text being cut)
    """
    # Draw the cover image full-bleed (edge to edge including bleed area)
    if os.path.exists(img_path):
        c.drawImage(img_path, img_x, img_y, width=img_w, height=img_h, preserveAspectRatio=False)
    else:
        c.setFillColor(HexColor("#f0e6d3"))
        c.rect(img_x, img_y, img_w, img_h, fill=1, stroke=0)
        c.setFillColor(SOFT_GREY)
        c.setFont("Helvetica", 9)
        c.drawCentredString(img_x + img_w/2, img_y + img_h/2, f"[ {os.path.basename(img_path)} ]")

    # Title text - white, centered in the safe content area
    cx = txt_x + txt_w / 2
    c.setFillColor(WHITE)

    c.setFont(F_BOLD, 42)
    c.drawCentredString(cx, txt_y + txt_h - 1.1 * inch, f"{name} and the")
    c.drawCentredString(cx, txt_y + txt_h - 1.75 * inch, "First Easter")

    c.setFont(F_IT, 18)
    c.drawCentredString(cx, txt_y + txt_h - 2.35 * inch, "A Named Story Book")


def render_back_cover(c, img_path, img_x, img_y, img_w, img_h, txt_x, txt_y, txt_w, txt_h):
    """
    Render the back cover: scene-09.jpg with quote and branding overlaid directly.
    No overlay box - text is placed directly on the artwork.

    img_x/y/w/h = image bounds (full bleed, extends to page edge for edge-to-edge printing)
    txt_x/y/w/h = text safe area (content area, inside trim to avoid text being cut)
    """
    # Draw scene-09 as background (full bleed edge-to-edge)
    if os.path.exists(img_path):
        c.drawImage(img_path, img_x, img_y, width=img_w, height=img_h, preserveAspectRatio=False)
    else:
        c.setFillColor(HexColor("#f0e6d3"))
        c.rect(img_x, img_y, img_w, img_h, fill=1, stroke=0)
        c.setFillColor(SOFT_GREY)
        c.setFont("Helvetica", 9)
        c.drawCentredString(img_x + img_w/2, img_y + img_h/2, f"[ {os.path.basename(img_path)} ]")

    # Text positioned within the safe content area (no dark overlay)
    cx = txt_x + txt_w / 2

    # Vertically center the text block in the content area
    block_h = 28 + 28 + 40 + 20 + 20 + 36 + 22 + 22  # total spacing
    text_y = txt_y + (txt_h + block_h) / 2

    # Isaiah 43:1 quote
    c.setFillColor(WHITE)
    c.setFont(F_IT, 16)
    c.drawCentredString(cx, text_y, "\u201cI have called you by name. You are mine.\u201d")
    text_y -= 28

    c.setFont(F_SEMI, 11)
    c.setFillColor(GOLD)
    c.drawCentredString(cx, text_y, "\u2014 ISAIAH 43:1")
    text_y -= 40

    # Tagline
    c.setFillColor(WHITE)
    c.setFont(F_IT, 12)
    c.drawCentredString(cx, text_y, "Before the world called him by any other name,")
    text_y -= 20
    c.drawCentredString(cx, text_y, "Jesus called him His own.")
    text_y -= 36

    # Brand
    c.setFont(F_SEMI, 14)
    c.setFillColor(GOLD)
    c.drawCentredString(cx, text_y, "THE NAMED STORY")
    text_y -= 22

    c.setFont(F_REG, 10)
    c.setFillColor(WHITE)
    c.drawCentredString(cx, text_y, "www.thenamedstory.com")


def render_spine(c, name, x, y, w, h):
    """
    Render the spine: solid color with vertical title text.

    x, y = bottom-left corner of the spine area (in PDF points)
    w, h = width and height of the spine area (in PDF points)
    """
    # Solid spine color
    c.setFillColor(SPINE_COLOR)
    c.rect(x, y, w, h, fill=1, stroke=0)

    # Only add text if spine is wide enough (> 8mm)
    if w > 8 * mm:
        c.saveState()
        c.setFillColor(GOLD)
        c.setFont(F_SEMI, 8)
        # Rotate text 90 degrees for vertical spine text
        cx = x + w / 2
        cy = y + h / 2
        c.translate(cx, cy)
        c.rotate(90)
        c.drawCentredString(0, -3, f"{name} and the First Easter")
        c.restoreState()


def render_joints(c, dims, page_h_pt):
    """Render the joint areas (narrow strips between spine and covers)."""
    # Joints are typically a neutral color
    for key in ["jointBackSize", "jointFrontSize"]:
        d = dims[key]
        x = d["left"] * mm
        y = (page_h_pt) - (d["top"] * mm) - (d["height"] * mm)
        w = d["width"] * mm
        h = d["height"] * mm
        c.setFillColor(SPINE_COLOR)
        c.rect(x, y, w, h, fill=1, stroke=0)


# ============================================================
# MAIN GENERATOR
# ============================================================
def generate_cover(name, variant, output, gelato_api_key=None, product_uid=None, page_count=30):
    """
    Generate the hardcover cover wrap PDF.

    Args:
        name:     Child's first name (for title personalization)
        variant:  Character variant (e.g. "boy-fair-blonde")
        output:   Output PDF file path
        gelato_api_key: Optional Gelato API key for fetching exact dimensions
        product_uid:    Optional Gelato product UID
        page_count:     Number of interior pages (affects spine width)

    Returns:
        output file path
    """
    register_fonts()

    # Get cover dimensions
    dims = get_cover_dimensions(gelato_api_key, product_uid, page_count)

    # Page size from wraparoundInsideSize (full bleed)
    page_w_mm = dims["wraparoundInsideSize"]["width"]
    page_h_mm = dims["wraparoundInsideSize"]["height"]
    page_w = page_w_mm * mm
    page_h = page_h_mm * mm

    print(f"\n  Cover wrap: {page_w_mm:.0f} \u00d7 {page_h_mm:.0f} mm")

    # Image paths
    img_dir = os.path.join(
        os.environ.get("IMAGES_BASE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "images")),
        variant
    )
    front_img = os.path.join(img_dir, "cover.jpg")
    back_img  = os.path.join(img_dir, "scene-09.jpg")

    # Create PDF
    c = canvas.Canvas(output, pagesize=(page_w, page_h))
    c.setTitle(f"{name} and the First Easter \u2014 Cover")
    c.setAuthor("The Named Story")

    # Fill entire page with spine color as base
    c.setFillColor(SPINE_COLOR)
    c.rect(0, 0, page_w, page_h, fill=1, stroke=0)

    # --- Calculate BLEED image areas (edge-to-edge) and CONTENT text areas ---
    # Back cover: image extends from left page edge to the joint
    jb = dims["jointBackSize"]
    back_img_x = 0
    back_img_y = 0
    back_img_w = jb["left"] * mm  # extends to where joint starts
    back_img_h = page_h           # full height including bleed

    # Back cover text safe area (contentBackSize)
    bd = dims["contentBackSize"]
    back_txt_x = bd["left"] * mm
    back_txt_y = page_h - (bd["top"] * mm) - (bd["height"] * mm)
    back_txt_w = bd["width"] * mm
    back_txt_h = bd["height"] * mm

    render_back_cover(c, back_img, back_img_x, back_img_y, back_img_w, back_img_h,
                      back_txt_x, back_txt_y, back_txt_w, back_txt_h)

    # --- JOINTS ---
    render_joints(c, dims, page_h)

    # --- SPINE (center) ---
    sd = dims["spineSize"]
    spine_x = sd["left"] * mm
    spine_y = page_h - (sd["top"] * mm) - (sd["height"] * mm)
    spine_w = sd["width"] * mm
    spine_h = sd["height"] * mm
    render_spine(c, name, spine_x, spine_y, spine_w, spine_h)

    # --- FRONT COVER (right side) ---
    # Front cover: image extends from after the front joint to right page edge
    jf = dims["jointFrontSize"]
    front_img_x = (jf["left"] + jf["width"]) * mm  # starts after front joint
    front_img_y = 0
    front_img_w = page_w - front_img_x              # extends to right page edge
    front_img_h = page_h                             # full height including bleed

    # Front cover text safe area (contentFrontSize)
    fd = dims["contentFrontSize"]
    front_txt_x = fd["left"] * mm
    front_txt_y = page_h - (fd["top"] * mm) - (fd["height"] * mm)
    front_txt_w = fd["width"] * mm
    front_txt_h = fd["height"] * mm

    render_front_cover(c, name, front_img, front_img_x, front_img_y, front_img_w, front_img_h,
                       front_txt_x, front_txt_y, front_txt_w, front_txt_h)

    c.showPage()
    c.save()

    kb = os.path.getsize(output) / 1024
    print(f"  \u2705 Cover generated: {output}")
    print(f"  {page_w_mm:.0f}\u00d7{page_h_mm:.0f}mm | {name} | {variant} | {kb:.0f} KB\n")

    return output


# ============================================================
# CLI
# ============================================================
if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Generate a Named Story cover wrap for Gelato hardcover")
    ap.add_argument("--name", required=True, help="Child's first name")
    ap.add_argument("--variant", required=True, help="Character variant (e.g. 'boy-fair-blonde')")
    ap.add_argument("--output", default=None, help="Output PDF filename")
    ap.add_argument("--pages", type=int, default=30, help="Interior page count (affects spine width)")
    ap.add_argument("--gelato-key", default=None, help="Gelato API key for fetching exact dimensions")
    ap.add_argument("--product-uid", default=None, help="Gelato product UID")
    a = ap.parse_args()

    if not a.output:
        a.output = f"{a.name.lower().replace(' ', '-')}-cover-wrap.pdf"

    generate_cover(a.name, a.variant, a.output, a.gelato_key, a.product_uid, a.pages)
